version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_root_password
      - db_wp_password
    volumes:
      - /home/aduenas-/data/mysql:/var/lib/mysql
    networks:
      - wp-network
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_wp_password
    depends_on:
      - mariadb
    volumes:
      - /home/aduenas-/data/wordpress:/var/www/html
    expose:
      - "${WORDPRESS_PHP_FPM_PORT}"
    networks:
      - wp-network
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/aduenas-/data/wordpress:/var/www/html:ro
      - ../certs:/etc/nginx/certs:ro
      - ./requeriments/nginx/conf:/etc/nginx/conf.d:ro
    networks:
      - wp-network
networks:
  wp-network:
    driver: bridge
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_wp_password:
    file: ../secrets/db_wp_password.txt
